FROM golang:1.13

WORKDIR /application

COPY . .

RUN go get github.com/mailru/easyjson/...
RUN go generate -v ./internal/pkg/models
RUN go get -d -v ./...
RUN go install -v ./cmd/chat/chat.go

EXPOSE 3000
CMD ["chat"]
