FROM golang:1.13

WORKDIR /application

COPY . .

RUN go get github.com/mailru/easyjson/...
RUN go get google.golang.org/grpc
RUN go get -d -u github.com/golang/protobuf/protoc-gen-go
RUN go install github.com/golang/protobuf/protoc-gen-go
RUN apt update && apt install protobuf-compiler -y
RUN ./scripts/generate.sh

RUN go get -d -v ./...

RUN go get -u github.com/go-delve/delve/cmd/dlv

RUN go build -v -gcflags "all=-N -l" ./cmd/chat/chat.go

EXPOSE 3000
EXPOSE 2345

CMD dlv --listen=:2345 --continue --headless=true --api-version=2 --accept-multiclient exec ./chat
