FROM golang:1.13

WORKDIR /application

COPY . .

RUN go get github.com/mailru/easyjson/...
RUN go generate -v ./internal/pkg/models

RUN go get -d -v ./...

RUN go get -u github.com/go-delve/delve/cmd/dlv
RUN go build -v -gcflags "all=-N -l" ./cmd/server/server.go

EXPOSE 3000
EXPOSE 2345
CMD dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec ./server
