FROM golang:1.13

WORKDIR /application

COPY . .

RUN go get github.com/mailru/easyjson/...
RUN go get google.golang.org/grpc
RUN go get -d -u github.com/golang/protobuf/protoc-gen-go
RUN go install github.com/golang/protobuf/protoc-gen-go
RUN apt update && apt install protobuf-compiler -y
RUN ./scripts/generate.sh

RUN go get -d -v ./...
RUN go build -v ./cmd/session/session.go


FROM alpine

WORKDIR /application

COPY --from=builder /application/session .

EXPOSE 3000

CMD ['./session']
