FROM golang:alpine AS builder

WORKDIR /application

COPY . .

RUN go get github.com/mailru/easyjson/...
RUN go get google.golang.org/grpc
RUN go get -d -u github.com/golang/protobuf/protoc-gen-go
RUN go install github.com/golang/protobuf/protoc-gen-go
RUN apk add protobuf bash
RUN ./scripts/generate.sh

RUN go get -d -v ./...
RUN go build -v ./cmd/server/server.go


FROM alpine

WORKDIR /application

COPY --from=builder /application/server .
COPY --from=builder /application/internal/pkg/pack/pack_schema.json .

EXPOSE 3000

CMD ["./server"]
